### ISSUE TITLE
Do any of the scripts in this project provide identification of TFs as pioneers using time series datasets?

### ISSUE THREAD

**Issue by rdbcasillas** [dlampart/csrproject#1]
Hello @dlampart ,

Thank you for this work and providing scripts on Github for replicating results. I was wondering if any of these scripts can be used over a time series dataset (I am working with ATAC-Seq peaks across multiple time points) to identify TFs as pioneers? Or will I have to run the whole pipeline on datasets from two developmental time points and then figure out the pioneers from that? Any ideas or suggestions are greatly appreciated. 

Thanks!

**Comment by dlampart** [comment]
Hi,

I guess you can give it a try. Although to get a signal, many disparate
cell types were neccessary in my case. There migtht also be a strategy that
leverages the time series nature of your data as pioneers are early
binders. my method doesnt uses that information.
